name: Cypress Tests

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.1' 

      - name: Install dependencies
        run: |
          npm ci  # Install dependencies using clean install

      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mochawesome

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos 
